[tool.poetry]
name = "2d-xray-generator"
version = "0.1.0"
description = ""
authors = ["harrison1125"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11, <=3.12"
numpy = '*'
seaborn = '*'
matplotlib = '*'
scipy = '*'
imageio = "^2.37.0"
pillow = "^11.3.0"
tifffile = "^2025.6.11"

[tool.poetry.scripts]
xrd-generate = "src.driver_codes.run_experiment:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
